### ISSUE TITLE
Mypal68 crashes on Amazon

### ISSUE THREAD

**Issue by NoNameNeeded2** [Feodor2/Mypal68#40] opened 2022-04-19 00:13 UTC
It happens very often that Mypal68 crashes on Amazon (you don't need to do anything special, it just happens every now and then, quite often actually).

This is the crash log file (or whatever it's called)
[e16_appcompat.txt](https://github.com/Feodor2/Mypal68/files/8508767/e16_appcompat.txt)

**Comment by Anbima** [comment] 2022-04-20 14:46
I can confirm this.

**Comment by Feodor2** [comment] 2022-04-22 10:57
i tried 'amazon.com' it thrown me that i am a robot and must do something cpacha
So i consider robots are who obey and do this stupid capcha, never shall open this stupid site sorry.

**Comment by Anbima** [comment] 2022-04-22 12:08
It is not the captcha.
It crashes when you open details pages of products.

**Comment by Feodor2** [comment] 2022-04-22 12:16
It does not let me in at all.  I hate that, it throws cpachta from the start so i avoid such shitsites.

**Comment by Anbima** [comment] 2022-04-22 12:21
Try to open this site:
https://www.amazon.de/AVM-High-End-MU-MIMO-VDSL-Supervectoring-DECT-Basis/dp/B071W8R4PS/ref=sr_1_3?__mk_de_DE=ÅMÅŽÕÑ&crid=AH7IWMCF820O&keywords=fritz+box&qid=1650630021&sprefix=fritz+bo%2Caps%2C195&sr=8-3

**Comment by Feodor2** [comment] 2022-04-23 11:01
It opened a page about selling some router did not crash though.

**Comment by Anbima** [comment] 2022-04-23 14:55
The site is displayed, but if you are waiting, Mypal crashes.
If he does not crash immediately, click on another link on the page.
At some point he stops and crashes.

**Comment by Feodor2** [comment] 2022-04-23 17:04
Waiting for a hour, did many differenet things on the page - no crash so far.
Pay attention that page quickly eats 500mb and you may get crash because out of memory.

**Comment by Anbima** [comment] 2022-04-23 17:21
It's not the memory.
The problem is browser.tabs.remote.autostart
I set this to false.
With true, the error does not come anymore, but the page needs a long time for loading.

Can browser.tabs.remote.autostart:true are now used, or is it still to BSOD?

**Comment by Anbima** [comment] 2022-04-23 17:34
The loading of a product page takes a long time and partially there are errors
![Uploading Screenshot.jpg…]()
.

**Comment by Anbima** [comment] 2022-04-23 17:43
browser.tabs.remote.autostart:true is not sure.
I had a BSOD at closing of Mypal.

**Comment by Feodor2** [comment] 2022-04-23 18:10
if browser.tabs.remote.autostart false it loads too much heavier but still does not crash. The error in your screen is not about crash but about slow heavy scripts - make continue then. Certainly the site has very bad usability without multiprocess.

**Comment by Anbima** [comment] 2022-04-23 18:22
The error message "Warung: Nicht antwortendes Script" from the picture above is with browser.tabs.remote.autostart:true

With browser.tabs.remote.autostart:false is the following error message:

![Screenshot](https://user-images.githubusercontent.com/49531928/164934844-6fa412c3-13f5-4827-978c-f34b346e7b54.jpg)

**Comment by NoNameNeeded2** [comment] 2022-04-25 18:15
Well, nothing has changed so far so amazon pages are still very prone to crash.

**Comment by RUvlad1** [comment] 2022-04-30 12:39
I tested this on a Windows XP Zver 2013 VM I had running rn and it seems to be working just fine
![Windows XP Zver 2013-2022-04-30-12-38-12](https://user-images.githubusercontent.com/60317461/166105969-62facddb-9969-4ab3-acfa-ef09cdde8c1a.png)

**Comment by INVorig** [comment] 2022-05-17 22:14
I would kindly like to confirm this error , as it happened to me just now. Open Amazon.de, pressed on the first item on display and without any message or delay, I was at my desktop and browser closed. (Same as if I had just closed the browser...)
by the way...  http://www.xe.com/currencyconverter/  is not working too, but only turns to white page (it works very slow, but works in MP29.3.0 ... )

**Closed** 2024-07-20 21:50 UTC
