### ISSUE TITLE
Mypal has issues on reddit.com and pw.com media and some misc issues

### ISSUE THREAD

**Issue by BEENNath58** [Feodor2/Mypal68#368] opened 2024-01-30 05:28 UTC
I am using Windows XP SP3, and also recently installed the POSReady updates to verify if anything changes but it doesn't. I am running an Ivy Bridge Pentium with 4GB of RAM

When I open reddit.com, the media doesn't load at all. It can be a GIF, a video, a photo and that part gets trimmed out of a post.

When I open a education site pw.com for subscribed lectures, the browser doesn't play the video and an error message that Mypal has stopped working comes up. 

Misc issues: 
1. The browser always asks me if it wants to be the default browser (IT IS) when it opens up regardless of checking or unchecking the checkbox.
2. [FIXED in new version] The browser doesn't find any updates and outputs a Firefox related error.
3. YouTube video has cropped in section
4. Some of the options don't work.

**Comment by JeanPaulLucien** [comment] 2024-01-31 16:16
Could you show screenshots?

**Comment by BEENNath58** [comment] 2024-02-01 11:45
Sure:

For reddit-

![1](https://github.com/Feodor2/Mypal68/assets/64649734/e18eafcf-22d8-4034-a97e-6dcea82ec64e)

There should be a video below "What do you think of these graphics?"

For PW-

![2](https://github.com/Feodor2/Mypal68/assets/64649734/cbbf8e49-17b8-4b9b-a076-73951d404c95)

This is what happens when I launch a video on their platform.

Misc issues-

3. Youtube video playback area is cropped in:
![3](https://github.com/Feodor2/Mypal68/assets/64649734/7a3b2323-c8e8-430a-b1d0-3594a5aca05b)

4. Mypal support and find more search engines do nothing:  
![4](https://github.com/Feodor2/Mypal68/assets/64649734/c2428937-4a08-422c-a93a-4796618b15c2)

**Comment by Feodor2** [comment] 2024-02-01 13:53
The reddot main page is broken for a while, likely it will be fixed upon 68.14 version, which i plan to make at best by next two months say by the end of the march.
For now you may use https://old.reddit.com/.

Other small things like "get more search" and "default browser" are broken in the very beginning, i think they such useless too and i wont waste the time for this, all time must be spent to do major things - ability to open and show good sites.

**Comment by JimMP68User** [comment] 2024-02-01 14:07
Maybe related to "#3 Youtube being cropped" - On the Rumble video site, if viewing livestream, the live chat box is cropped off at the bottom, and cannot make chat text since the text-entry area (below streaming chat display) is cut off. Used to work, and some months back this symptom cropped up. Win Xp SP3 Dell Optiplex 755 Core2 Duo 4GB ram and Mypal Ver 13.7b

The comments section works just fine. Only livestream chat is cropped.

Thanks in advance.

**Comment by BEENNath58** [comment] 2024-02-01 16:01
@Feodor2 Thanks.

Can you comment something about pw.live site? The homepage doesn't load, I have to use a copied link forl login site (actually pw.live redirects to the login site, and Mypal is stuck white in the homepage of the site).

The site works in browsers like XPchrome but its sluggish there (as no HW accel)

**Comment by Feodor2** [comment] 2024-02-01 17:54
> something about pw.live site

Yes i confirm, the site is too modern, it may be fixed or may not i cannot say for sure, the site has heavily tied to the goolag.

**Comment by BEENNath58** [comment] 2024-02-02 14:57
> > something about pw.live site
> 
> Yes i confirm, the site is too modern, it may be fixed or may not i cannot say for sure, the site has heavily tied to the goolag.

Ok thanks for your effort. I will be benefitted if that also gets fixed somehow., although I can live with the redirect link directly.

More importantly, there's a xui.dll crash when it playbacks a video, at least the video page loads there.

**Comment by Feodor2** [comment] 2024-02-02 17:37
How to reproduce the crash?
You are to provide actual link at least

**Comment by Feodor2** [comment] 2024-02-02 20:41
Then no way, soorry, put drwatson log may helps.

**Closed** 2024-07-20 20:35 UTC
