### ISSUE TITLE
dup

### ISSUE THREAD

**Issue by Jasantes** [Feodor2/Mypal68#535] opened 2024-10-26 02:41 UTC
https://download-installer.cdn.mozilla.net/pub/firefox/releases/68.12.0esr/win32/xpi

**Comment by zanud** [comment] 2024-10-26 12:19
Current Mypal 68.14.* is a mix of Firefox 68 and Firefox 78, so it's language packs are not directly compatible with Firefox's language packs of any version.

**Comment by Pikse** [comment] 2024-10-26 13:45
Duplicate of #203

**Closed** 2024-10-26 15:48 UTC
